# ─────────────────────────────────────────────────────────────────────────────
# variables.tf — the "knobs" of this stack. Every value you might change per
# environment lives here as a variable. You DO NOT edit this file per-env;
# instead you pass a *.tfvars file (see dev.tfvars.example / prod.tfvars.example)
# or answer the prompts. That is how one set of code builds both dev and prod.
# ─────────────────────────────────────────────────────────────────────────────

variable "region" {
  description = "AWS region to deploy into. Pick the one closest to your users. eu-central-1 = Frankfurt (good for Israel/EU)."
  type        = string
  default     = "eu-central-1"
}

variable "environment" {
  description = "Short name for this environment: dev or prod. Used in resource names/tags so the two never collide."
  type        = string
  default     = "dev"

  validation {
    # Guard-rail: only 'dev' or 'prod' allowed, so a typo doesn't create a third
    # ghost environment.
    condition     = contains(["dev", "prod"], var.environment)
    error_message = "environment must be either \"dev\" or \"prod\"."
  }
}

variable "instance_type" {
  # ── WHY ARM / Graviton by default ─────────────────────────────────────────
  # t4g.* are AWS Graviton (ARM) instances. They cost ~20% LESS than the equal
  # Intel t3.* size AND our whole stack (Node 20, nginx, mongo, caddy) all ship
  # native arm64 images — so there is no downside. That is why the default is
  # ARM. t4g.small = 2 vCPU / 2 GB RAM (~$0.0168/hr in eu-central-1).
  #
  # COST TRADEOFF you can choose instead:
  #   t4g.micro  1 vCPU / 1 GB  ~$0.0084/hr  — cheapest; fine for DEV only.
  #   t3.micro   2 vCPU / 1 GB  ~$0.0104/hr  — Intel; only pick if you MUST run
  #                                            an x86-only image (we don't).
  #   t4g.small  2 vCPU / 2 GB  ~$0.0168/hr  — recommended for PROD (Mongo + all
  #                                            containers want the extra 1 GB).
  # NOTE: t3.micro is x86_64. If you switch to it you must also flip
  # var.cpu_architecture to "x86_64" so the AMI lookup matches (see main.tf).
  description = "EC2 size. ARM t4g.* is cheapest and fully supported. See the cost notes in this file."
  type        = string
  default     = "t4g.small"
}

variable "cpu_architecture" {
  description = "CPU family of the AMI to boot: arm64 (for t4g.*, cheapest) or x86_64 (for t3.*). MUST match instance_type."
  type        = string
  default     = "arm64"

  validation {
    condition     = contains(["arm64", "x86_64"], var.cpu_architecture)
    error_message = "cpu_architecture must be \"arm64\" or \"x86_64\"."
  }
}

variable "allowed_ssh_cidr" {
  # A CIDR is an IP range. "203.0.113.7/32" = exactly one IP (your home/office).
  # "0.0.0.0/0" = the whole internet — NEVER do that for SSH in prod. Find your
  # current IP with:  curl ifconfig.me   → then use "<that-ip>/32".
  description = "IP range allowed to SSH (port 22). Lock this to YOUR ip as x.x.x.x/32. Do not leave it open to the world."
  type        = string
  default     = "0.0.0.0/0" # deliberately loud default so you remember to change it
}

variable "key_name" {
  description = "Name of an EXISTING EC2 key pair in this region, OR the name Terraform will create from public_key_path (see create_key_pair)."
  type        = string
  default     = "kehilapp-key"
}

variable "create_key_pair" {
  description = "true = Terraform uploads your local public key as a new EC2 key pair named key_name. false = key_name already exists in AWS, just reference it."
  type        = bool
  default     = true
}

variable "public_key_path" {
  description = "Path to your SSH PUBLIC key on this machine (only used when create_key_pair = true). Generate with: ssh-keygen -t ed25519 -f ~/.ssh/kehilapp"
  type        = string
  default     = "~/.ssh/kehilapp.pub"
}

variable "domain" {
  description = "Domain the site will serve on (e.g. kehilapp.example.com). Passed to the box so Caddy can request an HTTPS cert. Leave empty to run plain HTTP by IP."
  type        = string
  default     = ""
}

variable "root_volume_gb" {
  description = "Size of the server's disk (EBS gp3) in GB. Mongo data + docker images live here. 20 GB is plenty for dev; 30 for prod."
  type        = number
  default     = 20
}

variable "repo_url" {
  description = "Public git URL of THIS devops repo. user_data clones it on boot so the server has docker-compose.prod.yml + nginx/caddy configs. Leave default if unsure and copy files manually."
  type        = string
  default     = "https://github.com/OWNER/kehilapp-devops.git"
}

variable "assign_elastic_ip" {
  description = "true = give the box a fixed public IP (Elastic IP) that survives stop/start. Recommended for prod (DNS points at it). A first EIP attached to a running instance is free."
  type        = bool
  default     = true
}
